sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
env:
  - ANSIBLE=2.2
  - ANSIBLE=2.3
  - ANSIBLE=2.4
  - ANSIBLE=2.5
matrix:
  fast_finish: true
  allow_failures:
    - python: "3.7-dev"
    - env: ANSIBLE=2.5
install: pip install tox-travis
script:
  - tox
